[build]
  base = "web"
  publish = "web/dist"
  command = "npm run build:no-check"

[build.environment]
  NODE_VERSION = "18"

# Install all dependencies including workspace packages
[build.processing]
  skip_processing = false

[[headers]]
  for = "/assets/*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/*.css"  
  [headers.values]
    Content-Type = "text/css; charset=utf-8"
    Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 